In [17]:
import pandas as pd
import numpy as np
import os
import glob

cwd = os.getcwd()
data_dir = os.path.join(cwd, "data")
if not os.path.exists(data_dir):
    data_dir = os.path.abspath(os.path.join(cwd, "..", "..", "data"))

In [18]:
path_xls = os.path.join(data_dir, "zipcodes_num_nl_2025.xls")
path_zipcodes = os.path.join(data_dir, "zipcodes_num_nl_2025.csv")

if os.path.exists(path_xls) and not os.path.exists(path_zipcodes):
    temp_df = pd.read_excel(path_xls)
    temp_df.to_csv(path_zipcodes, index=False)

In [19]:
path_staff = os.path.join(data_dir, "fietsvergoedingen_personeel_HOGENT_2024_2025.csv")
path_bluebike = os.path.join(data_dir, "bluebikes", "blue_bike_full_data.csv")
path_telpalen = os.path.join(data_dir, "telpalen", "GeoLocation", "telpalen_final_with_geoLocation.csv")

weather_station_pattern = os.path.join(data_dir, "weatherData", "aws_station", "aws_station_*.csv")
weather_station_files = glob.glob(weather_station_pattern)
path_weather_station = weather_station_files[0] if weather_station_files else None

zipcodes_df = pd.read_csv(path_zipcodes)
zipcodes_df.columns = zipcodes_df.columns.str.strip().str.lower()
staff_df = pd.read_csv(path_staff, sep=";")
blue_bike_df = pd.read_csv(path_bluebike, sep=";")
telpalen_df = pd.read_csv(path_telpalen, sep=";")
weather_station_df = pd.read_csv(path_weather_station, sep=",") if path_weather_station else pd.DataFrame()

In [20]:
weather_station_df

,WeatherStationID,Name,Altitude,Latitude,Longitude,Point,Province,SnapshotDate
0,6414,BEITEM,24.80,50.904,3.122,(50.904 3.122),West-Vlaanderen,2026-02-24
1,6438,STABROEK,4.00,51.325,4.364,(51.325 4.364),Antwerpen,2026-02-24
2,6464,RETIE,21.50,51.221,5.027,(51.221 5.027),Antwerpen,2026-02-24
3,6447,UCCLE,100.60,50.797,4.358,(50.797 4.358),Brussel,2026-02-24
4,6434,MELLE,15.00,50.980,3.816,(50.98 3.816),Oost-Vlaanderen,2026-02-24
5,6459,ERNAGE,159.20,50.582,4.689,(50.582 4.689),Namen,2026-02-24
6,6439,SINT-KATELIJNE-WAVER,8.30,51.075,4.525,(51.075 4.525),Antwerpen,2026-02-24
7,6418,ZEEBRUGGE,12.10,51.348,3.202,(51.348 3.202),West-Vlaanderen,2026-02-24
8,6455,DOURBES,234.80,50.096,4.595,(50.096 4.595),Namen,2026-02-24
9,6472,HUMAIN,295.30,50.194,5.255,(50.194 5.255),Luxemburg,2026-02-24
10,6484,BUZENOL,323.90,49.620,5.587,(49.62 5.587),Luxemburg,2026-02-24
11,10101002,DE HAAN,3.66,51.280,3.074,(51.28 3.074),West-Vlaanderen,2026-02-24
12,6494,MONT RIGI,673.20,50.511,6.073,(50.511 6.073),Luik,2026-02-24
13,6477,DIEPENBEEK,39.30,50.916,5.450,(50.916 5.45),Limburg,2026-02-24

In [21]:
zipcodes_df.head()

,postcode,plaatsnaam,deelgemeente,hoofdgemeente,provincie
0,612,Sinterklaas,NaN,Sinterklaas,NaN
1,1000,Brussel,Neen,BRUSSEL,BRUSSEL
2,1005,Verenigde Vergadering van de Gemeenschappelijke,NaN,Verenigde Vergadering van de Gemeenschappelijke,NaN
3,1006,Raad van de Vlaamse Gemeenschapscommissie,NaN,Raad van de Vlaamse Gemeenschapscommissie,NaN
4,1007,Assemblée de la Commission Communautaire Franç...,NaN,Assemblée de la Commission Communautaire Franç...,NaN

In [22]:
telpalen_df.head()

,CountingPointID,CustomID,CountingPointName,Latitude,Longitude,FirstData,Granularity,Directional,DomainID,DomainName,Description,PostalCode,Municipality,MainMunicipality,Province,LocationKey
0,100052870,Fietstel_Aalst2,Aalst - Fietspad Merestraat (Noord),50.935490,4.015710,2019-07-16,PT15M,True,6517,Vlaamse Overheid A. Wegen en Verkeer,NaN,9300,Aalst,Aalst,Oost-Vlaanderen,2547
1,100052883,Fietstel_Aalst1,Aalst F414 Fietspad Merestraat (West),50.934180,4.014436,2019-07-24,PT15M,True,6517,Vlaamse Overheid A. Wegen en Verkeer,NaN,9300,Aalst,Aalst,Oost-Vlaanderen,2547
2,100052871,Fietstel_Aalst3,Aalst F414 Fietspad Merestraat (Zuid),50.933850,4.016470,2019-07-16,PT15M,True,6517,Vlaamse Overheid A. Wegen en Verkeer,NaN,9300,Aalst,Aalst,Oost-Vlaanderen,2547
3,300027871,Fietstel_Aalter1,Aalter - Knokkebaan,51.105837,3.435059,2022-09-30,PT15M,True,6517,Vlaamse Overheid A. Wegen en Verkeer,NaN,9880,Aalter,Aalter,Oost-Vlaanderen,2728
4,300025932,Fietstel_Aarschot1,Aarschot - Ter Heidelaan,50.990840,4.812590,2022-07-14,PT15M,True,6517,Vlaamse Overheid A. Wegen en Verkeer,NaN,3200,Aarschot,Aarschot,Vlaams-Brabant,471

In [23]:
weather_station_df

,WeatherStationID,Name,Altitude,Latitude,Longitude,Point,Province,SnapshotDate
0,6414,BEITEM,24.80,50.904,3.122,(50.904 3.122),West-Vlaanderen,2026-02-24
1,6438,STABROEK,4.00,51.325,4.364,(51.325 4.364),Antwerpen,2026-02-24
2,6464,RETIE,21.50,51.221,5.027,(51.221 5.027),Antwerpen,2026-02-24
3,6447,UCCLE,100.60,50.797,4.358,(50.797 4.358),Brussel,2026-02-24
4,6434,MELLE,15.00,50.980,3.816,(50.98 3.816),Oost-Vlaanderen,2026-02-24
5,6459,ERNAGE,159.20,50.582,4.689,(50.582 4.689),Namen,2026-02-24
6,6439,SINT-KATELIJNE-WAVER,8.30,51.075,4.525,(51.075 4.525),Antwerpen,2026-02-24
7,6418,ZEEBRUGGE,12.10,51.348,3.202,(51.348 3.202),West-Vlaanderen,2026-02-24
8,6455,DOURBES,234.80,50.096,4.595,(50.096 4.595),Namen,2026-02-24
9,6472,HUMAIN,295.30,50.194,5.255,(50.194 5.255),Luxemburg,2026-02-24
10,6484,BUZENOL,323.90,49.620,5.587,(49.62 5.587),Luxemburg,2026-02-24
11,10101002,DE HAAN,3.66,51.280,3.074,(51.28 3.074),West-Vlaanderen,2026-02-24
12,6494,MONT RIGI,673.20,50.511,6.073,(50.511 6.073),Luik,2026-02-24
13,6477,DIEPENBEEK,39.30,50.916,5.450,(50.916 5.45),Limburg,2026-02-24

In [24]:
weather_station_df.head()

,WeatherStationID,Name,Altitude,Latitude,Longitude,Point,Province,SnapshotDate
0,6414,BEITEM,24.8,50.904,3.122,(50.904 3.122),West-Vlaanderen,2026-02-24
1,6438,STABROEK,4.0,51.325,4.364,(51.325 4.364),Antwerpen,2026-02-24
2,6464,RETIE,21.5,51.221,5.027,(51.221 5.027),Antwerpen,2026-02-24
3,6447,UCCLE,100.6,50.797,4.358,(50.797 4.358),Brussel,2026-02-24
4,6434,MELLE,15.0,50.980,3.816,(50.98 3.816),Oost-Vlaanderen,2026-02-24

In [25]:
dim_location = zipcodes_df[["postcode", "plaatsnaam", "hoofdgemeente", "provincie"]].drop_duplicates().reset_index(drop=True)
dim_location.columns = ["PostalCode", "Municipality", "MainMunicipality", "Province"]
dim_location.insert(0, "LocationKey", range(1, len(dim_location) + 1))
dim_location = dim_location.assign(Latitude=np.nan, Longitude=np.nan, Address=np.nan)

loc_ref = dim_location[["LocationKey", "PostalCode", "Municipality", "Province"]]

dim_staff = staff_df.merge(loc_ref, left_on="Postcode of postcode groep", right_on="PostalCode", how="left") \
    [["PersoneelsID", "Entiteit", "Hoofdcampus", "LocationKey"]] \
    .rename(columns={"PersoneelsID": "StaffID", "Entiteit": "Entity", "Hoofdcampus": "Departure"})

dim_blue_bike = blue_bike_df.merge(loc_ref, on=["PostalCode", "Municipality"], how="left") \
    .assign(HasTrainConnection=1) \
    [["Location", "Address", "HasTrainConnection", "URL", "LocationKey"]]

dim_counting_point = telpalen_df.merge(loc_ref, left_on=["PostalCode", "Municipality"], right_on=["PostalCode", "Municipality"], how="left") 

station_mapping = {
    "BEITEM": "ROESELARE",
    "UCCLE": "UKKEL",
    "MONT RIGI": "WEISMES",
}
dim_weather_station = weather_station_df[['WeatherStationID', 'Name', 'Altitude', 'Longitude', 'Latitude', 'SnapshotDate']].copy()
dim_weather_station["MatchName"] = dim_weather_station["Name"].str.strip().str.upper().replace(station_mapping)
dim_loc_lookup = dim_location[["LocationKey", "Municipality"]].copy()
dim_loc_lookup["Municipality"] = dim_loc_lookup["Municipality"].str.strip().str.upper()
dim_weather_station = dim_weather_station.merge(
    dim_loc_lookup.drop_duplicates("Municipality"), 
    left_on="MatchName", 
    right_on="Municipality", 
    how="left"
).drop(columns=["MatchName", "Municipality"])

In [26]:
dim_weather_station

,WeatherStationID,Name,Altitude,Longitude,Latitude,SnapshotDate,LocationKey
0,6414,BEITEM,24.80,3.122,50.904,2026-02-24,2405
1,6438,STABROEK,4.00,4.364,51.325,2026-02-24,418
2,6464,RETIE,21.50,5.027,51.221,2026-02-24,351
3,6447,UCCLE,100.60,4.358,50.797,2026-02-24,42
4,6434,MELLE,15.00,3.816,50.980,2026-02-24,2486
5,6459,ERNAGE,159.20,4.689,50.582,2026-02-24,1164
6,6439,SINT-KATELIJNE-WAVER,8.30,4.525,51.075,2026-02-24,400
7,6418,ZEEBRUGGE,12.10,3.202,51.348,2026-02-24,2248
8,6455,DOURBES,234.80,4.595,50.096,2026-02-24,1499
9,6472,HUMAIN,295.30,5.255,50.194,2026-02-24,1815
10,6484,BUZENOL,323.90,5.587,49.620,2026-02-24,1710
11,10101002,DE HAAN,3.66,3.074,51.280,2026-02-24,2252
12,6494,MONT RIGI,673.20,6.073,50.511,2026-02-24,1126
13,6477,DIEPENBEEK,39.30,5.450,50.916,2026-02-24,592

In [27]:
loc_ref

,LocationKey,PostalCode,Municipality,Province
0,1,612,Sinterklaas,NaN
1,2,1000,Brussel,BRUSSEL
2,3,1005,Verenigde Vergadering van de Gemeenschappelijke,NaN
3,4,1006,Raad van de Vlaamse Gemeenschapscommissie,NaN
4,5,1007,Assemblée de la Commission Communautaire Franç...,NaN
...,...,...,...,...
2759,2760,9988,Waterland-Oudeman,OOST-VLAANDEREN
2760,2761,9988,Watervliet,OOST-VLAANDEREN
2761,2762,9990,Maldegem,OOST-VLAANDEREN
2762,2763,9991,Adegem,OOST-VLAANDEREN
2763,2764,9992,Middelburg,OOST-VLAANDEREN

In [28]:
output_dir = os.path.join(data_dir, "DimLocationData")
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

dim_location.to_csv(os.path.join(output_dir, "DimLocation.csv"), index=False)
dim_staff.to_csv(os.path.join(output_dir, "DimStaff.csv"), index=False)
dim_blue_bike.to_csv(os.path.join(output_dir, "DimBlueBikeStation.csv"), index=False)
dim_counting_point.to_csv(os.path.join(output_dir, "DimCountingPoint.csv"), index=False)
dim_weather_station.to_csv(os.path.join(output_dir, "DimWeatherStation.csv"), index=False)

print(f"Bestanden succesvol opgeslagen")

Bestanden succesvol opgeslagen