In [2]:
import pandas as pd
import requests
from pathlib import Path
import sys

ROOT = Path().resolve().parents[1] 
sys.path.append(str(ROOT))

from data_gathering.dimLocation.initializer import getLocationKey

In [3]:
file_path = ROOT / "data" / "DEPI_HOGENT_mobiliteitsbevraging_2024.csv"

In [4]:
file_path = ROOT / "data" / "DEPI_HOGENT_mobiliteitsbevraging_2024.csv"

if not file_path.exists():
    print(f"FOUT: Bestand niet gevonden op: {file_path}")
else:
    df = pd.read_csv(file_path, sep=";", encoding='unicode_escape')

In [5]:
df.head()

,StartDate,EndDate,Status,Progress,Duration__in_seconds_,Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,...,infrastructuur_3,leeftijd,functie,functie_6_TEXT,werkrooster,geslacht,gender,gender_4_TEXT,postcode,kansen
0,23/09/2024 2:04,24/09/2024 7:47,0,760,1070330,0,1/10/2024 7:47,R_1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,23/09/2024 4:13,24/09/2024 7:48,0,760,993070,0,1/10/2024 7:48,R_2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20/09/2024 6:08,24/09/2024 8:16,0,60,3532910,0,1/10/2024 8:16,R_3,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1/10/2024 12:09,1/10/2024 12:15,0,1000,4090,10,1/10/2024 12:16,R_4,NaN,NaN,...,30.0,450.0,10.0,NaN,10.0,20.0,20.0,NaN,90000.0,NaN
4,1/10/2024 12:14,1/10/2024 12:23,0,1000,5200,10,1/10/2024 12:23,R_5,NaN,NaN,...,10.0,390.0,10.0,NaN,10.0,20.0,20.0,NaN,93100.0,Fietsleasing

### Alleen relevante data bijhouden

In [6]:
df = df[['RecordedDate', 'ResponseId', 'LocationLatitude', 'LocationLongitude','werkplek', 'pendeltijd', 'pendelafstand', 'vervoermiddel', 'Finished', 'functie', 'werk__', 'thuiswerk']]

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 665 entries, 0 to 664
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   RecordedDate       665 non-null    str
 1   ResponseId         665 non-null    str
 2   LocationLatitude   530 non-null    float64
 3   LocationLongitude  530 non-null    float64
 4   werkplek           650 non-null    float64
 5   pendeltijd         605 non-null    float64
 6   pendelafstand      605 non-null    float64
 7   vervoermiddel      605 non-null    float64
 8   Finished           665 non-null    int64
 9   functie            524 non-null    float64
 10  werk__             605 non-null    float64
 11  thuiswerk          605 non-null    float64
dtypes: float64(9), int64(1), str(2)
memory usage: 62.5 KB

In [11]:
df.head(10)

,RecordedDate,ResponseId,LocationLatitude,LocationLongitude,werkplek,pendeltijd,pendelafstand,vervoermiddel,Finished,functie,werk__,thuiswerk,DateTime,TimeKey
0,1/10/2024 7:47,R_1,NaN,NaN,70.0,120.0,30.0,100.0,0,NaN,60.0,40.0,2024-01-10 07:47:00,747
1,1/10/2024 7:48,R_2,NaN,NaN,50.0,120.0,30.0,150.0,0,NaN,40.0,40.0,2024-01-10 07:48:00,748
2,1/10/2024 8:16,R_3,NaN,NaN,80.0,NaN,NaN,NaN,0,NaN,NaN,NaN,2024-01-10 08:16:00,816
3,1/10/2024 12:16,R_4,51047.0,37206.0,80.0,200.0,60.0,100.0,10,10.0,60.0,40.0,2024-01-10 12:16:00,1216
4,1/10/2024 12:23,R_5,51047.0,37206.0,70.0,550.0,400.0,10.0,10,10.0,60.0,40.0,2024-01-10 12:23:00,1223
5,1/10/2024 12:24,R_6,51096.0,38319.0,80.0,550.0,250.0,100.0,10,70.0,60.0,30.0,2024-01-10 12:24:00,1224
6,1/10/2024 12:35,R_7,508854.0,33581.0,80.0,100.0,20.0,100.0,10,10.0,60.0,20.0,2024-01-10 12:35:00,1235
7,1/10/2024 13:12,R_8,508847.0,45049.0,70.0,450.0,250.0,100.0,10,20.0,60.0,30.0,2024-01-10 13:12:00,1312
8,1/10/2024 13:33,R_9,509347.0,41296.0,80.0,600.0,360.0,100.0,10,40.0,60.0,10.0,2024-01-10 13:33:00,1333
9,1/10/2024 13:59,R_10,509475.0,31205.0,20.0,750.0,360.0,10.0,10,20.0,60.0,30.0,2024-01-10 13:59:00,1359

In [10]:
df['DateTime'] = pd.to_datetime(df['RecordedDate'], format='mixed')

# 2. Formatteer naar HHMM als string ('%H%M')
df['TimeKey'] = df['DateTime'].dt.strftime('%H%M')

# 3. Omzetten naar een getal (integer)
df['TimeKey'] = df['TimeKey'].astype(int)

In [73]:
def corrigeer_lat(val):
    lengte = len(str(val).replace('.', ''))
    
    if lengte == 6: # Bijv. 5104.0 (5 cijfers)
        return val / 1000
    elif lengte == 7: # Bijv. 50885.0 (6 cijfers)
        return val / 10000
    else:
        return val

In [74]:
df['LocationLatitude'] = df['LocationLatitude'].apply(corrigeer_lat)
df['LocationLongitude'] = df['LocationLongitude'] / 10000

### Add geolocation

In [75]:
def get_vlaanderen_data(lat, lon):
    url = f"https://geo.api.vlaanderen.be/geolocation/v4/Location?latlon={lat},{lon}"
    try:
        r = requests.get(url, timeout=5)
        res = r.json().get('LocationResult', []) # print als je de res is wilt zien van de api
        if res:
            return str(res[0].get('Zipcode')) # enkel postcode eruit halen
    except:
        pass
    return None

In [76]:
ZIPCODE_FILE = ROOT / "data" / "zipcodes_num_nl_2025.xls"

In [77]:
df_zip = pd.read_excel(ZIPCODE_FILE)

In [78]:
df_zip.info()

<class 'pandas.DataFrame'>
RangeIndex: 2764 entries, 0 to 2763
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Postcode       2764 non-null   int64
 1   Plaatsnaam     2764 non-null   str
 2   Deelgemeente   2720 non-null   str
 3   Hoofdgemeente  2764 non-null   str
 4   Provincie      2720 non-null   str
dtypes: int64(1), str(4)
memory usage: 108.1 KB

In [79]:
for index, row in df.iterrows():
    print(f"plaats {index} ophalen van de {len(df)}")
    lat, lon = row['LocationLatitude'], row['LocationLongitude']

    if pd.isna(lat) or pd.isna(lon):
        print(f"geen lat en/of longtitude gevonden voor plaats {index}")
        continue
    
    pc = get_vlaanderen_data(lat, lon)
    
    if pc:
        match_excel = df_zip[df_zip['Postcode'] == int(pc)]
        
        if not match_excel.empty:
            mainMunicipality = match_excel.iloc[0]['Hoofdgemeente'].capitalize()
            municipality = match_excel.iloc[0]['Plaatsnaam'].capitalize()
            province = match_excel.iloc[0]['Provincie'].title()
            
            df.at[index, "LocationKey"] = getLocationKey(postalCode=pc, MainMunicipality=mainMunicipality, Municipality=municipality, Province=province)
            print(f"{municipality} met postcode {pc} has been found!")
        else:
            print(f"Postcode {pc} gevonden via API, maar staat niet in de Excel lijst.")

plaats 0 ophalen van de 665
geen lat en/of longtitude gevonden voor plaats 0
plaats 1 ophalen van de 665
geen lat en/of longtitude gevonden voor plaats 1
plaats 2 ophalen van de 665
geen lat en/of longtitude gevonden voor plaats 2
plaats 3 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 4 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 5 ophalen van de 665
Beervelde met postcode 9080 has been found!
plaats 6 ophalen van de 665
Desselgem met postcode 8792 has been found!
plaats 7 ophalen van de 665
Nossegem met postcode 1930 has been found!
plaats 8 ophalen van de 665
Baardegem met postcode 9310 has been found!
plaats 9 ophalen van de 665
Beveren met postcode 8800 has been found!
plaats 10 ophalen van de 665
Gontrode met postcode 9090 has been found!
plaats 11 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 12 ophalen van de 665
Sint-amandsberg met postcode 9040 has been found!
plaats 13 ophalen van de 665
Ertvelde met postcode 9940 has been found!
plaats 14 ophalen van de 665
Loppem met postcode 8210 has been found!
plaats 15 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 16 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 17 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 18 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 19 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 20 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 21 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 22 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 23 ophalen van de 665
Zomergem met postcode 9930 has been found!
plaats 24 ophalen van de 665
plaats 25 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 26 ophalen van de 665
plaats 27 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 28 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 29 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 30 ophalen van de 665
Bevere met postcode 9700 has been found!
plaats 31 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 32 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 33 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 34 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 35 ophalen van de 665
Drongen met postcode 9031 has been found!
plaats 36 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 37 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 38 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 39 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 40 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 41 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 42 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 43 ophalen van de 665
geen lat en/of longtitude gevonden voor plaats 43
plaats 44 ophalen van de 665
Sint-amandsberg met postcode 9040 has been found!
plaats 45 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 46 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 47 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 48 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 49 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 50 ophalen van de 665
Bevere met postcode 9700 has been found!
plaats 51 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 52 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 53 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 54 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 55 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 56 ophalen van de 665
Elene met postcode 9620 has been found!
plaats 57 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 58 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 59 ophalen van de 665
Edegem met postcode 2650 has been found!
plaats 60 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 61 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 62 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 63 ophalen van de 665
geen lat en/of longtitude gevonden voor plaats 63
plaats 64 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 65 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 66 ophalen van de 665
Harelbeke met postcode 8530 has been found!
plaats 67 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 68 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 69 ophalen van de 665
Aalter met postcode 9880 has been found!
plaats 70 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 71 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 72 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 73 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 74 ophalen van de 665
Destelbergen met postcode 9070 has been found!
plaats 75 ophalen van de 665
Torhout met postcode 8820 has been found!
plaats 76 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 77 ophalen van de 665
geen lat en/of longtitude gevonden voor plaats 77
plaats 78 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 79 ophalen van de 665
Daknam met postcode 9160 has been found!
plaats 80 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 81 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 82 ophalen van de 665
Bevere met postcode 9700 has been found!
plaats 83 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 84 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 85 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 86 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 87 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 88 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 89 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 90 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 91 ophalen van de 665
Waregem met postcode 8790 has been found!
plaats 92 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 93 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 94 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 95 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 96 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 97 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 98 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 99 ophalen van de 665
plaats 100 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 101 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 102 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 103 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 104 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 105 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 106 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 107 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 108 ophalen van de 665
Antwerpen met postcode 2000 has been found!
plaats 109 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 110 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 111 ophalen van de 665
Gentbrugge met postcode 9050 has been found!
plaats 112 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 113 ophalen van de 665
geen lat en/of longtitude gevonden voor plaats 113
plaats 114 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 115 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 116 ophalen van de 665
Schellebelle met postcode 9260 has been found!
plaats 117 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 118 ophalen van de 665
Bevere met postcode 9700 has been found!
plaats 119 ophalen van de 665
Oostende met postcode 8400 has been found!
plaats 120 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 121 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 122 ophalen van de 665
Bevere met postcode 9700 has been found!
plaats 123 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 124 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 125 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 126 ophalen van de 665
Schaarbeek met postcode 1030 has been found!
plaats 127 ophalen van de 665
Emelgem met postcode 8870 has been found!
plaats 128 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 129 ophalen van de 665
Schaarbeek met postcode 1030 has been found!
plaats 130 ophalen van de 665
Elene met postcode 9620 has been found!
plaats 131 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 132 ophalen van de 665
Affligem met postcode 1790 has been found!
plaats 133 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 134 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 135 ophalen van de 665
Antwerpen met postcode 2000 has been found!
plaats 136 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 137 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 138 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 139 ophalen van de 665
Zele met postcode 9240 has been found!
plaats 140 ophalen van de 665
Astene met postcode 9800 has been found!
plaats 141 ophalen van de 665
Outer met postcode 9406 has been found!
plaats 142 ophalen van de 665
Machelen met postcode 9870 has been found!
plaats 143 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 144 ophalen van de 665
Appels met postcode 9200 has been found!
plaats 145 ophalen van de 665
Kortrijk met postcode 8500 has been found!
plaats 146 ophalen van de 665
Waterland-oudeman met postcode 9988 has been found!
plaats 147 ophalen van de 665
Sint-jans-molenbeek met postcode 1080 has been found!
plaats 148 ophalen van de 665
Gentbrugge met postcode 9050 has been found!
plaats 149 ophalen van de 665
Astene met postcode 9800 has been found!
plaats 150 ophalen van de 665
Knesselare met postcode 9910 has been found!
plaats 151 ophalen van de 665
Gentbrugge met postcode 9050 has been found!
plaats 152 ophalen van de 665
Oostende met postcode 8400 has been found!
plaats 153 ophalen van de 665
Geraardsbergen met postcode 9500 has been found!
plaats 154 ophalen van de 665
Deurne met postcode 2100 has been found!
plaats 155 ophalen van de 665
Astene met postcode 9800 has been found!
plaats 156 ophalen van de 665
Sint-amandsberg met postcode 9040 has been found!
plaats 157 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 158 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 159 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 160 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 161 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 162 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 163 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 164 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 165 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 166 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 167 ophalen van de 665
Brugge met postcode 8000 has been found!
plaats 168 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 169 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 170 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 171 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 172 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 173 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 174 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 175 ophalen van de 665
Assebroek met postcode 8310 has been found!
plaats 176 ophalen van de 665
plaats 177 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 178 ophalen van de 665
Bost met postcode 3300 has been found!
plaats 179 ophalen van de 665
Dudzele met postcode 8380 has been found!
plaats 180 ophalen van de 665
Aalst met postcode 9300 has been found!
plaats 181 ophalen van de 665
plaats 182 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 183 ophalen van de 665
Koksijde met postcode 8670 has been found!
plaats 184 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 185 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 186 ophalen van de 665
Harelbeke met postcode 8530 has been found!
plaats 187 ophalen van de 665
Bottelare met postcode 9820 has been found!
plaats 188 ophalen van de 665
Elene met postcode 9620 has been found!
plaats 189 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 190 ophalen van de 665
Berlare met postcode 9290 has been found!
plaats 191 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 192 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 193 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 194 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 195 ophalen van de 665
Torhout met postcode 8820 has been found!
plaats 196 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 197 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 198 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 199 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 200 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 201 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 202 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 203 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 204 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 205 ophalen van de 665
Waregem met postcode 8790 has been found!
plaats 206 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 207 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 208 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 209 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 210 ophalen van de 665
Sint-jans-molenbeek met postcode 1080 has been found!
plaats 211 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 212 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 213 ophalen van de 665
Astene met postcode 9800 has been found!
plaats 214 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 215 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 216 ophalen van de 665
Schaarbeek met postcode 1030 has been found!
plaats 217 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 218 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 219 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 220 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 221 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 222 ophalen van de 665
Sint-jans-molenbeek met postcode 1080 has been found!
plaats 223 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 224 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 225 ophalen van de 665
Sint-amandsberg met postcode 9040 has been found!
plaats 226 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 227 ophalen van de 665
Laken met postcode 1020 has been found!
plaats 228 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 229 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 230 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 231 ophalen van de 665
Daknam met postcode 9160 has been found!
plaats 232 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 233 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 234 ophalen van de 665
Elene met postcode 9620 has been found!
plaats 235 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 236 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 237 ophalen van de 665
Beveren met postcode 8800 has been found!
plaats 238 ophalen van de 665
Astene met postcode 9800 has been found!
plaats 239 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 240 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 241 ophalen van de 665
plaats 242 ophalen van de 665
Ooigem met postcode 8710 has been found!
plaats 243 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 244 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 245 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 246 ophalen van de 665
plaats 247 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 248 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 249 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 250 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 251 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 252 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 253 ophalen van de 665
plaats 254 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 255 ophalen van de 665
plaats 256 ophalen van de 665
Bredene met postcode 8450 has been found!
plaats 257 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 258 ophalen van de 665
Middelkerke met postcode 8430 has been found!
plaats 259 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 260 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 261 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 262 ophalen van de 665
Gontrode met postcode 9090 has been found!
plaats 263 ophalen van de 665
Schaarbeek met postcode 1030 has been found!
plaats 264 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 265 ophalen van de 665
Astene met postcode 9800 has been found!
plaats 266 ophalen van de 665
Destelbergen met postcode 9070 has been found!
plaats 267 ophalen van de 665
Elene met postcode 9620 has been found!
plaats 268 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 269 ophalen van de 665
Zomergem met postcode 9930 has been found!
plaats 270 ophalen van de 665
Gontrode met postcode 9090 has been found!
plaats 271 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 272 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 273 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 274 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 275 ophalen van de 665
Aalst met postcode 9300 has been found!
plaats 276 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 277 ophalen van de 665
Aalst met postcode 9300 has been found!
plaats 278 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 279 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 280 ophalen van de 665
Sint-andries met postcode 8200 has been found!
plaats 281 ophalen van de 665
Daknam met postcode 9160 has been found!
plaats 282 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 283 ophalen van de 665
plaats 284 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 285 ophalen van de 665
Balegem met postcode 9860 has been found!
plaats 286 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 287 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 288 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 289 ophalen van de 665
Gent met postcode 9000 has been found!
plaats 290 ophalen van de 665

In [80]:
df.columns

Index(['RecordedDate', 'ResponseId', 'LocationLatitude', 'LocationLongitude',
       'werkplek', 'pendeltijd', 'pendelafstand', 'vervoermiddel', 'Finished',
       'functie', 'werk__', 'thuiswerk', 'LocationKey'],
      dtype='str')

In [81]:
for i in df.columns[4:]:
    df[i] = df[i] / 10

In [82]:
import json

with open(ROOT / "data" / "DEPI_meta_dict_HOGENT_mobiliteitsbevraging_2024.json", 'r', encoding='utf-8') as file:
    metadata = json.load(file)

In [ ]:
def apply_mapping(df, column_name, map_dict):
    # Zorg dat de sleutels in de map_dict floats zijn, 
    # omdat de data in het dataframe vaak floats zijn.
    cleaned_map = {float(k): v for k, v in map_dict.items()}
    df[column_name] = df[column_name].map(cleaned_map)
    return df

In [84]:
for i in df.columns[4:]:
    if i in metadata['variable_value_labels']:
        df = apply_mapping(df, i, metadata['variable_value_labels'][i])

In [85]:
df.head()

,RecordedDate,ResponseId,LocationLatitude,LocationLongitude,werkplek,pendeltijd,pendelafstand,vervoermiddel,Finished,functie,werk__,thuiswerk,LocationKey
0,1/10/2024 7:47,R_1,NaN,NaN,Mercator,12.0,3.0,Fiets of elektrische fiets (speed pedelec inbe...,False,NaN,100% (voltijdse betrekking),Thuiswerk 2 dagen/week,NaN
1,1/10/2024 7:48,R_2,NaN,NaN,Ledeganck,12.0,3.0,Trein,False,NaN,60% - 79%,Thuiswerk 2 dagen/week,NaN
2,1/10/2024 8:16,R_3,NaN,NaN,"Schoonmeersen Noord (gebouwen B,C,D, E, P, S)",NaN,NaN,NaN,False,NaN,NaN,NaN,NaN
3,1/10/2024 12:16,R_4,51.047,3.7206,"Schoonmeersen Noord (gebouwen B,C,D, E, P, S)",20.0,6.0,Fiets of elektrische fiets (speed pedelec inbe...,True,Administratief personeel,100% (voltijdse betrekking),Thuiswerk 2 dagen/week,246.3
4,1/10/2024 12:23,R_5,51.047,3.7206,Mercator,55.0,40.0,"Wagen, bestelwagen of vrachtwagen alleen of me...",True,Administratief personeel,100% (voltijdse betrekking),Thuiswerk 2 dagen/week,246.3

In [ ]:
df = df.rename(columns={
    'RecordedDate': 'RecordDate',
    'ResponseId': 'ResponseID',
    'LocationLatitude': 'Latitude',
    'LocationLongitude': 'Longtitude',
    'werkplek': 'WorkPlace',
    'pendeltijd': 'TravelTime',
    'pendelafstand': 'TravelDistance',
    'vervoermiddel': 'TravelType',
    "functie": "WorkoFunction",
    "werk__": "WorkRegime",
    'thuiswerk': "HomeWork"
})

In [87]:
df['RecordDate'] = pd.to_datetime(df['RecordDate'], format="%d/%m/%Y %H:%M").dt.strftime('%Y%m%d')

In [88]:
df["RecordDate"] = df["RecordDate"].astype("Int64")

In [92]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 665 entries, 0 to 664
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   RecordDate      665 non-null    Int64
 1   ResponseID      665 non-null    str
 2   Latitude        530 non-null    float64
 3   Longtitude      530 non-null    float64
 4   WorkPlace       650 non-null    str
 5   TravelTime      605 non-null    float64
 6   TravelDistance  605 non-null    float64
 7   TravelType      605 non-null    str
 8   Finished        665 non-null    str
 9   Function        524 non-null    str
 10  WorkRegime      605 non-null    str
 11  HomeWork        605 non-null    str
 12  LocationKey     497 non-null    float64
dtypes: Int64(1), float64(5), str(7)
memory usage: 68.3 KB

In [90]:
df.head()

,RecordDate,ResponseID,Latitude,Longtitude,WorkPlace,TravelTime,TravelDistance,TravelType,Finished,functie,WorkRegime,HomeWork,LocationKey
0,20241001,R_1,NaN,NaN,Mercator,12.0,3.0,Fiets of elektrische fiets (speed pedelec inbe...,False,NaN,100% (voltijdse betrekking),Thuiswerk 2 dagen/week,NaN
1,20241001,R_2,NaN,NaN,Ledeganck,12.0,3.0,Trein,False,NaN,60% - 79%,Thuiswerk 2 dagen/week,NaN
2,20241001,R_3,NaN,NaN,"Schoonmeersen Noord (gebouwen B,C,D, E, P, S)",NaN,NaN,NaN,False,NaN,NaN,NaN,NaN
3,20241001,R_4,51.047,3.7206,"Schoonmeersen Noord (gebouwen B,C,D, E, P, S)",20.0,6.0,Fiets of elektrische fiets (speed pedelec inbe...,True,Administratief personeel,100% (voltijdse betrekking),Thuiswerk 2 dagen/week,246.3
4,20241001,R_5,51.047,3.7206,Mercator,55.0,40.0,"Wagen, bestelwagen of vrachtwagen alleen of me...",True,Administratief personeel,100% (voltijdse betrekking),Thuiswerk 2 dagen/week,246.3