In [1]:
import pandas as pd
from pathlib import Path
import sys

ROOT = Path().resolve().parents[1] 
sys.path.append(str(ROOT))

from data_gathering.telpalen.telpalen_aantal_fietsers import haal_all_counts
from DWH.connection.connect import get_engine, getData
from data_gathering.telpalen.telpalen_locatie_fetcher import haal_telpalen_volledig_op
from data_gathering.hulp_functies import find_gemeente_in_location, get_nominatim_data

In [2]:
engine = get_engine()
df_telpalen = haal_telpalen_volledig_op(engine)
dim_location = getData(engine, query="SELECT * FROM DimLocation")

Reeds aanwezig in DimCountingPoint: 356 rijen

In [3]:
# Hernoemen kolommen
df_telpalen = df_telpalen.rename(columns={
    'counting_point_id' : 'CountingPointID',
    'customId' : 'CustomID',
    'name' : 'CountingPointName',
    'latitude' : 'Latitude',
    'longitude' :  'Longitude',
    'firstData' : 'FirstData',
    'lastData' : 'LastData',
    'granularity' : 'Granularity',
    'directional' : 'Directional',
    'direction_name_in' : 'DirectionNameIn',
    'direction_name_out' : 'DirectionNameOut',
    'domain_id' : 'DomainID',
    'domain_name' : 'DomainName',
    'description' : 'Description'
})

In [4]:
print(df_telpalen.info())

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Empty DataFrame
None

In [5]:
for index, row in df_telpalen.iterrows():
    naam = str(row['CountingPointName'])
    lat, lon = row['Latitude'], row['Longitude']
    pc = row['postcode']

    match = pd.DataFrame()

    if pc:
        try:
            match = dim_location[dim_location['PostalCode'] == pc]
        except (ValueError, AttributeError):
            match = pd.DataFrame()

    if len(match) == 1:
        municipality = str(match.iloc[0]['Municipality'])
    else:
        pc, municipality = get_nominatim_data(lat, lon)
    
    try:
        matchLocation = dim_location[(dim_location['PostalCode'] == pc) & (dim_location['Municipality'] == municipality.title())]
    except:
        print(f"pc = {pc}, municipality = {municipality}, index = {index}")
        print(f"PROBLEEM: [{index + 1}/{len(df_telpalen)}] Postcode = {pc}, loc = {naam}, mun = {municipality}, lat = {lat}, lon = {lon}")
        continue
    
    # als postcode en municipality niet matchen, zoek dan enkel op municipality
    if matchLocation.empty:
        matchLocation = dim_location[dim_location['Municipality'] == municipality.title()]

    # Geen match op municipality, zoek juiste Municipality met locatie naam
    if matchLocation.empty:
            municipality = find_gemeente_in_location(naam, locaties=match['Municipality'].tolist())
            matchLocation = dim_location[(dim_location['PostalCode'] == pc) & (dim_location['Municipality'] == municipality.title())]
    try:
        location_key = matchLocation.iloc[0].LocationKey
        df_telpalen.at[index,'LocationKey'] = location_key
        # print(f"[{index + 1}/{len(df_bluebike)}] Postcode = {pc}, loc = {row['LocationName']}, mun = {municipality}")
    except:
        print(f"PROBLEEM: [{index + 1}/{len(df_telpalen)}] Postcode = {pc}, loc = {naam}, mun = {municipality}, lat = {lat}, lon = {lon}")

In [6]:
df_telpalen

Empty DataFrame
Columns: []
Index: []

In [7]:
# dim_countingpoint = df_telpalen[[
#     "CountingPointID",
#     "CustomID",
#     "CountingPointName",
#     "Latitude",
#     "Longitude",
#     "FirstData",
#     "LastData",
#     "Granularity",
#     "Directional",
#     "DirectionNameIn",
#     "DirectionNameOut",
#     "DomainID",
#     "DomainName",
#     "Description",
#     "LocationKey"
# ]]
# dim_countingpoint["CountingPointID"] = dim_countingpoint["CountingPointID"].astype(int)
# dim_countingpoint["Latitude"] = dim_countingpoint["Latitude"].astype(float)
# dim_countingpoint["Longitude"] = dim_countingpoint["Longitude"].astype(float)
# dim_countingpoint["LocationKey"] = dim_countingpoint["LocationKey"].astype(int)

dim_countingpoint = getData(engine, query="SELECT * FROM DimCountingPoint")

dim_countingpoint.info()

<class 'pandas.DataFrame'>
RangeIndex: 356 entries, 0 to 355
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CountingPointID    356 non-null    int64
 1   CustomID           256 non-null    str
 2   CountingPointName  356 non-null    str
 3   Latitude           356 non-null    float64
 4   Longitude          356 non-null    float64
 5   FirstData          356 non-null    object
 6   Granularity        356 non-null    str
 7   Directional        356 non-null    bool
 8   DirectionNameIn    349 non-null    str
 9   DirectionNameOut   337 non-null    str
 10  DomainID           356 non-null    int64
 11  DomainName         356 non-null    str
 12  Description        116 non-null    str
 13  LocationKey        356 non-null    int64
dtypes: bool(1), float64(2), int64(3), object(1), str(7)
memory usage: 36.6+ KB

In [8]:
df_counts = haal_all_counts(dim_countingpoint, engine)

[1/356] ophalen data voor paal 100038932
Succes: Delete uitgevoerd
[2/356] ophalen data voor paal 100044065
Geen nieuwe data.
[3/356] ophalen data voor paal 100044847
Succes: Delete uitgevoerd
[4/356] ophalen data voor paal 100044848
Succes: Delete uitgevoerd
[5/356] ophalen data voor paal 100044849
Succes: Delete uitgevoerd
[6/356] ophalen data voor paal 100044850
Succes: Delete uitgevoerd
[7/356] ophalen data voor paal 100044851
Succes: Delete uitgevoerd
[8/356] ophalen data voor paal 100044852
Succes: Delete uitgevoerd
[9/356] ophalen data voor paal 100044853
Succes: Delete uitgevoerd
[10/356] ophalen data voor paal 100046096
Succes: Delete uitgevoerd
[11/356] ophalen data voor paal 100047495
Succes: Delete uitgevoerd
[12/356] ophalen data voor paal 100047496
Succes: Delete uitgevoerd
[13/356] ophalen data voor paal 100048586
Succes: Delete uitgevoerd
[14/356] ophalen data voor paal 100048587
Succes: Delete uitgevoerd
[15/356] ophalen data voor paal 100048588
Succes: Delete uitgevoerd
[16/356] ophalen data voor paal 100048589
Succes: Delete uitgevoerd
[17/356] ophalen data voor paal 100048590
Succes: Delete uitgevoerd
[18/356] ophalen data voor paal 100048591
Succes: Delete uitgevoerd
[19/356] ophalen data voor paal 100048592
Succes: Delete uitgevoerd
[20/356] ophalen data voor paal 100048593
Succes: Delete uitgevoerd
[21/356] ophalen data voor paal 100048594
Succes: Delete uitgevoerd
[22/356] ophalen data voor paal 100048595
Succes: Delete uitgevoerd
[23/356] ophalen data voor paal 100049156
Succes: Delete uitgevoerd
[24/356] ophalen data voor paal 100049157
Succes: Delete uitgevoerd
[25/356] ophalen data voor paal 100049158
Succes: Delete uitgevoerd
[26/356] ophalen data voor paal 100049159
Succes: Delete uitgevoerd
[27/356] ophalen data voor paal 100049160
Succes: Delete uitgevoerd
[28/356] ophalen data voor paal 100049254
Succes: Delete uitgevoerd
[29/356] ophalen data voor paal 100049255
Succes: Delete uitgevoerd
[30/356] ophalen data voor paal 100049256
Succes: Delete uitgevoerd
[31/356] ophalen data voor paal 100049257
Succes: Delete uitgevoerd
[32/356] ophalen data voor paal 100049258
Succes: Delete uitgevoerd
[33/356] ophalen data voor paal 100049259
Succes: Delete uitgevoerd
[34/356] ophalen data voor paal 100050645
Succes: Delete uitgevoerd
[35/356] ophalen data voor paal 100050646
Succes: Delete uitgevoerd
[36/356] ophalen data voor paal 100052862
Succes: Delete uitgevoerd
[37/356] ophalen data voor paal 100052863
Succes: Delete uitgevoerd
[38/356] ophalen data voor paal 100052864
Succes: Delete uitgevoerd
[39/356] ophalen data voor paal 100052865
Succes: Delete uitgevoerd
[40/356] ophalen data voor paal 100052866
Succes: Delete uitgevoerd
[41/356] ophalen data voor paal 100052867
Succes: Delete uitgevoerd
[42/356] ophalen data voor paal 100052868
Succes: Delete uitgevoerd
[43/356] ophalen data voor paal 100052869
Succes: Delete uitgevoerd
[44/356] ophalen data voor paal 100052870
Succes: Delete uitgevoerd
[45/356] ophalen data voor paal 100052871
Succes: Delete uitgevoerd
[46/356] ophalen data voor paal 100052872
Succes: Delete uitgevoerd
[47/356] ophalen data voor paal 100052873
Succes: Delete uitgevoerd
[48/356] ophalen data voor paal 100052874
Succes: Delete uitgevoerd
[49/356] ophalen data voor paal 100052875
Succes: Delete uitgevoerd
[50/356] ophalen data voor paal 100052876
Succes: Delete uitgevoerd
[51/356] ophalen data voor paal 100052877
Succes: Delete uitgevoerd
[52/356] ophalen data voor paal 100052878
Succes: Delete uitgevoerd
[53/356] ophalen data voor paal 100052879
Succes: Delete uitgevoerd
[54/356] ophalen data voor paal 100052880
Succes: Delete uitgevoerd
[55/356] ophalen data voor paal 100052881
Succes: Delete uitgevoerd
[56/356] ophalen data voor paal 100052882
Succes: Delete uitgevoerd
[57/356] ophalen data voor paal 100052883
Succes: Delete uitgevoerd
[58/356] ophalen data voor paal 100052884
Succes: Delete uitgevoerd
[59/356] ophalen data voor paal 100054732
Succes: Delete uitgevoerd
[60/356] ophalen data voor paal 100054733
Succes: Delete uitgevoerd
[61/356] ophalen data voor paal 100054734
Succes: Delete uitgevoerd
[62/356] ophalen data voor paal 100054735
Succes: Delete uitgevoerd
[63/356] ophalen data voor paal 100055619
Succes: Delete uitgevoerd
[64/356] ophalen data voor paal 100055620
Succes: Delete uitgevoerd
[65/356] ophalen data voor paal 100056189
Succes: Delete uitgevoerd
[66/356] ophalen data voor paal 100057134
Succes: Delete uitgevoerd
[67/356] ophalen data voor paal 300015729
Succes: Delete uitgevoerd
[68/356] ophalen data voor paal 300015730
Succes: Delete uitgevoerd
[69/356] ophalen data voor paal 300015731
Succes: Delete uitgevoerd
[70/356] ophalen data voor paal 300018525
Succes: Delete uitgevoerd
[71/356] ophalen data voor paal 300018526
Succes: Delete uitgevoerd
[72/356] ophalen data voor paal 300019056
Succes: Delete uitgevoerd
[73/356] ophalen data voor paal 300019223
Succes: Delete uitgevoerd
[74/356] ophalen data voor paal 300019372
Succes: Delete uitgevoerd
[75/356] ophalen data voor paal 300019379
Succes: Delete uitgevoerd
[76/356] ophalen data voor paal 300019380
Succes: Delete uitgevoerd
[77/356] ophalen data voor paal 300019839
Succes: Delete uitgevoerd
[78/356] ophalen data voor paal 300020940
Succes: Delete uitgevoerd
[79/356] ophalen data voor paal 300021045
Succes: Delete uitgevoerd
[80/356] ophalen data voor paal 300021108
Succes: Delete uitgevoerd
[81/356] ophalen data voor paal 300021145
Succes: Delete uitgevoerd
[82/356] ophalen data voor paal 300021158
Succes: Delete uitgevoerd
[83/356] ophalen data voor paal 300021614
Succes: Delete uitgevoerd
[84/356] ophalen data voor paal 300023447
Succes: Delete uitgevoerd
[85/356] ophalen data voor paal 300023449
Succes: Delete uitgevoerd
[86/356] ophalen data voor paal 300023450
Succes: Delete uitgevoerd
[87/356] ophalen data voor paal 300023451
Succes: Delete uitgevoerd
[88/356] ophalen data voor paal 300023452
Succes: Delete uitgevoerd
[89/356] ophalen data voor paal 300023453
Succes: Delete uitgevoerd
[90/356] ophalen data voor paal 300023486
Succes: Delete uitgevoerd
[91/356] ophalen data voor paal 300023487
Succes: Delete uitgevoerd
[92/356] ophalen data voor paal 300023488
Succes: Delete uitgevoerd
[93/356] ophalen data voor paal 300023527
Succes: Delete uitgevoerd
[94/356] ophalen data voor paal 300023528
Succes: Delete uitgevoerd
[95/356] ophalen data voor paal 300023529
Succes: Delete uitgevoerd
[96/356] ophalen data voor paal 300023530
Succes: Delete uitgevoerd
[97/356] ophalen data voor paal 300023581
Succes: Delete uitgevoerd
[98/356] ophalen data voor paal 300023582
Succes: Delete uitgevoerd
[99/356] ophalen data voor paal 300023680
Succes: Delete uitgevoerd
[100/356] ophalen data voor paal 300023682
Succes: Delete uitgevoerd
[101/356] ophalen data voor paal 300023741
Succes: Delete uitgevoerd
[102/356] ophalen data voor paal 300023743
Succes: Delete uitgevoerd
[103/356] ophalen data voor paal 300023874
Succes: Delete uitgevoerd
[104/356] ophalen data voor paal 300024198
Succes: Delete uitgevoerd
[105/356] ophalen data voor paal 300024443
Succes: Delete uitgevoerd
[106/356] ophalen data voor paal 300024444
Succes: Delete uitgevoerd
[107/356] ophalen data voor paal 300024454
Succes: Delete uitgevoerd
[108/356] ophalen data voor paal 300024455
Succes: Delete uitgevoerd
[109/356] ophalen data voor paal 300024459
Geen nieuwe data.
[110/356] ophalen data voor paal 300024499
Succes: Delete uitgevoerd
[111/356] ophalen data voor paal 300024500
Succes: Delete uitgevoerd
[112/356] ophalen data voor paal 300024504
Succes: Delete uitgevoerd
[113/356] ophalen data voor paal 300024505
Succes: Delete uitgevoerd
[114/356] ophalen data voor paal 300024549
Succes: Delete uitgevoerd
[115/356] ophalen data voor paal 300024550
Succes: Delete uitgevoerd
[116/356] ophalen data voor paal 300024551
Succes: Delete uitgevoerd
[117/356] ophalen data voor paal 300024552
Succes: Delete uitgevoerd
[118/356] ophalen data voor paal 300024592
Succes: Delete uitgevoerd
[119/356] ophalen data voor paal 300024594
Succes: Delete uitgevoerd
[120/356] ophalen data voor paal 300025204
Succes: Delete uitgevoerd
[121/356] ophalen data voor paal 300025205
Succes: Delete uitgevoerd
[122/356] ophalen data voor paal 300025206
Succes: Delete uitgevoerd
[123/356] ophalen data voor paal 300025380
Succes: Delete uitgevoerd
[124/356] ophalen data voor paal 300025382
Succes: Delete uitgevoerd
[125/356] ophalen data voor paal 300025383
Succes: Delete uitgevoerd
[126/356] ophalen data voor paal 300025572
Succes: Delete uitgevoerd
[127/356] ophalen data voor paal 300025573
Succes: Delete uitgevoerd
[128/356] ophalen data voor paal 300025574
Succes: Delete uitgevoerd
[129/356] ophalen data voor paal 300025575
Succes: Delete uitgevoerd
[130/356] ophalen data voor paal 300025576
Succes: Delete uitgevoerd
[131/356] ophalen data voor paal 300025577
Succes: Delete uitgevoerd
[132/356] ophalen data voor paal 300025580
Succes: Delete uitgevoerd
[133/356] ophalen data voor paal 300025592
Succes: Delete uitgevoerd
[134/356] ophalen data voor paal 300025593
Succes: Delete uitgevoerd
[135/356] ophalen data voor paal 300025808
Succes: Delete uitgevoerd
[136/356] ophalen data voor paal 300025809
Succes: Delete uitgevoerd
[137/356] ophalen data voor paal 300025810
Succes: Delete uitgevoerd
[138/356] ophalen data voor paal 300025811
Succes: Delete uitgevoerd
[139/356] ophalen data voor paal 300025812
Succes: Delete uitgevoerd
[140/356] ophalen data voor paal 300025813
Succes: Delete uitgevoerd
[141/356] ophalen data voor paal 300025814
Succes: Delete uitgevoerd
[142/356] ophalen data voor paal 300025855
Succes: Delete uitgevoerd
[143/356] ophalen data voor paal 300025856
Succes: Delete uitgevoerd
[144/356] ophalen data voor paal 300025932
Succes: Delete uitgevoerd
[145/356] ophalen data voor paal 300025933
Succes: Delete uitgevoerd
[146/356] ophalen data voor paal 300025934
Succes: Delete uitgevoerd
[147/356] ophalen data voor paal 300026025
Succes: Delete uitgevoerd
[148/356] ophalen data voor paal 300026026
Succes: Delete uitgevoerd
[149/356] ophalen data voor paal 300026086
Succes: Delete uitgevoerd
[150/356] ophalen data voor paal 300026087
Succes: Delete uitgevoerd
[151/356] ophalen data voor paal 300026090
Succes: Delete uitgevoerd
[152/356] ophalen data voor paal 300026104
Geen nieuwe data.
[153/356] ophalen data voor paal 300026105
Geen nieuwe data.
[154/356] ophalen data voor paal 300026110
Succes: Delete uitgevoerd
[155/356] ophalen data voor paal 300026111
Succes: Delete uitgevoerd
[156/356] ophalen data voor paal 300026136
Succes: Delete uitgevoerd
[157/356] ophalen data voor paal 300026137
Succes: Delete uitgevoerd
[158/356] ophalen data voor paal 300026274
Succes: Delete uitgevoerd
[159/356] ophalen data voor paal 300026275
Succes: Delete uitgevoerd
[160/356] ophalen data voor paal 300026302
Succes: Delete uitgevoerd
[161/356] ophalen data voor paal 300026303
Succes: Delete uitgevoerd
[162/356] ophalen data voor paal 300026348
Succes: Delete uitgevoerd
[163/356] ophalen data voor paal 300026349
Succes: Delete uitgevoerd
[164/356] ophalen data voor paal 300026758
Succes: Delete uitgevoerd
[165/356] ophalen data voor paal 300026820
Succes: Delete uitgevoerd
[166/356] ophalen data voor paal 300026861
Succes: Delete uitgevoerd
[167/356] ophalen data voor paal 300026986
Succes: Delete uitgevoerd
[168/356] ophalen data voor paal 300027064
Succes: Delete uitgevoerd
[169/356] ophalen data voor paal 300027129
Succes: Delete uitgevoerd
[170/356] ophalen data voor paal 300027489
Succes: Delete uitgevoerd
[171/356] ophalen data voor paal 300027499
Succes: Delete uitgevoerd
[172/356] ophalen data voor paal 300027871
Succes: Delete uitgevoerd
[173/356] ophalen data voor paal 300027878
Succes: Delete uitgevoerd
[174/356] ophalen data voor paal 300027879
Succes: Delete uitgevoerd
[175/356] ophalen data voor paal 300027898
Succes: Delete uitgevoerd
[176/356] ophalen data voor paal 300027900
Succes: Delete uitgevoerd
[177/356] ophalen data voor paal 300027919
Succes: Delete uitgevoerd
[178/356] ophalen data voor paal 300027923
Succes: Delete uitgevoerd
[179/356] ophalen data voor paal 300027931
Succes: Delete uitgevoerd
[180/356] ophalen data voor paal 300027967
Succes: Delete uitgevoerd
[181/356] ophalen data voor paal 300028325
Succes: Delete uitgevoerd
[182/356] ophalen data voor paal 300028358
Succes: Delete uitgevoerd
[183/356] ophalen data voor paal 300028385
Succes: Delete uitgevoerd
[184/356] ophalen data voor paal 300028477
Succes: Delete uitgevoerd
[185/356] ophalen data voor paal 300028478
Succes: Delete uitgevoerd
[186/356] ophalen data voor paal 300028984
Succes: Delete uitgevoerd
[187/356] ophalen data voor paal 300029061
Succes: Delete uitgevoerd
[188/356] ophalen data voor paal 300029091
Succes: Delete uitgevoerd
[189/356] ophalen data voor paal 300029164
Succes: Delete uitgevoerd
[190/356] ophalen data voor paal 300030111
Succes: Delete uitgevoerd
[191/356] ophalen data voor paal 300030471
Succes: Delete uitgevoerd
[192/356] ophalen data voor paal 300030472
Succes: Delete uitgevoerd
[193/356] ophalen data voor paal 300030476
Succes: Delete uitgevoerd
[194/356] ophalen data voor paal 300030477
Succes: Delete uitgevoerd
[195/356] ophalen data voor paal 300030728
Succes: Delete uitgevoerd
[196/356] ophalen data voor paal 300031561
Succes: Delete uitgevoerd
[197/356] ophalen data voor paal 300031574
Succes: Delete uitgevoerd
[198/356] ophalen data voor paal 300031607
Succes: Delete uitgevoerd
[199/356] ophalen data voor paal 300031927
Succes: Delete uitgevoerd
[200/356] ophalen data voor paal 300035955
Succes: Delete uitgevoerd
[201/356] ophalen data voor paal 300035984
Succes: Delete uitgevoerd
[202/356] ophalen data voor paal 300035985
Succes: Delete uitgevoerd
[203/356] ophalen data voor paal 300036060
Succes: Delete uitgevoerd
[204/356] ophalen data voor paal 300037402
Geen nieuwe data.
[205/356] ophalen data voor paal 300039260
Succes: Delete uitgevoerd
[206/356] ophalen data voor paal 300039581
Succes: Delete uitgevoerd
[207/356] ophalen data voor paal 300041340
Succes: Delete uitgevoerd
[208/356] ophalen data voor paal 300042151
Succes: Delete uitgevoerd
[209/356] ophalen data voor paal 300042152
Succes: Delete uitgevoerd
[210/356] ophalen data voor paal 300042153
Succes: Delete uitgevoerd
[211/356] ophalen data voor paal 300042154
Succes: Delete uitgevoerd
[212/356] ophalen data voor paal 300042155
Succes: Delete uitgevoerd
[213/356] ophalen data voor paal 300042156
Succes: Delete uitgevoerd
[214/356] ophalen data voor paal 300042157
Succes: Delete uitgevoerd
[215/356] ophalen data voor paal 300042158
Succes: Delete uitgevoerd
[216/356] ophalen data voor paal 300042159
Succes: Delete uitgevoerd
[217/356] ophalen data voor paal 300042160
Succes: Delete uitgevoerd
[218/356] ophalen data voor paal 300042161
Succes: Delete uitgevoerd
[219/356] ophalen data voor paal 300042162
Succes: Delete uitgevoerd
[220/356] ophalen data voor paal 300042163
Succes: Delete uitgevoerd
[221/356] ophalen data voor paal 300042164
Succes: Delete uitgevoerd
[222/356] ophalen data voor paal 300042165
Succes: Delete uitgevoerd
[223/356] ophalen data voor paal 300042166
Succes: Delete uitgevoerd
[224/356] ophalen data voor paal 300042167
Succes: Delete uitgevoerd
[225/356] ophalen data voor paal 300042168
Succes: Delete uitgevoerd
[226/356] ophalen data voor paal 300042169
Succes: Delete uitgevoerd
[227/356] ophalen data voor paal 300042170
Succes: Delete uitgevoerd
[228/356] ophalen data voor paal 300042171
Succes: Delete uitgevoerd
[229/356] ophalen data voor paal 300042172
Succes: Delete uitgevoerd
[230/356] ophalen data voor paal 300042173
Succes: Delete uitgevoerd
[231/356] ophalen data voor paal 300042174
Succes: Delete uitgevoerd
[232/356] ophalen data voor paal 300042175
Succes: Delete uitgevoerd
[233/356] ophalen data voor paal 300042176
Succes: Delete uitgevoerd
[234/356] ophalen data voor paal 300042177
Succes: Delete uitgevoerd
[235/356] ophalen data voor paal 300042178
Succes: Delete uitgevoerd
[236/356] ophalen data voor paal 300042179
Succes: Delete uitgevoerd
[237/356] ophalen data voor paal 300042180
Geen nieuwe data.
[238/356] ophalen data voor paal 300042181
Succes: Delete uitgevoerd
[239/356] ophalen data voor paal 300042182
Succes: Delete uitgevoerd
[240/356] ophalen data voor paal 300042183
Succes: Delete uitgevoerd
[241/356] ophalen data voor paal 300042184
Succes: Delete uitgevoerd
[242/356] ophalen data voor paal 300042185
Succes: Delete uitgevoerd
[243/356] ophalen data voor paal 300042186
Succes: Delete uitgevoerd
[244/356] ophalen data voor paal 300042187
Succes: Delete uitgevoerd
[245/356] ophalen data voor paal 300042188
Succes: Delete uitgevoerd
[246/356] ophalen data voor paal 300042189
Succes: Delete uitgevoerd
[247/356] ophalen data voor paal 300042190
Succes: Delete uitgevoerd
[248/356] ophalen data voor paal 300042191
Succes: Delete uitgevoerd
[249/356] ophalen data voor paal 300042192
Succes: Delete uitgevoerd
[250/356] ophalen data voor paal 300042193
Succes: Delete uitgevoerd
[251/356] ophalen data voor paal 300042194
Succes: Delete uitgevoerd
[252/356] ophalen data voor paal 300042195
Succes: Delete uitgevoerd
[253/356] ophalen data voor paal 300042196
Succes: Delete uitgevoerd
[254/356] ophalen data voor paal 300042197
Succes: Delete uitgevoerd
[255/356] ophalen data voor paal 300042198
Succes: Delete uitgevoerd
[256/356] ophalen data voor paal 300042199
Succes: Delete uitgevoerd
[257/356] ophalen data voor paal 300042200
Succes: Delete uitgevoerd
[258/356] ophalen data voor paal 300042201
Succes: Delete uitgevoerd
[259/356] ophalen data voor paal 300042202
Succes: Delete uitgevoerd
[260/356] ophalen data voor paal 300042203
Succes: Delete uitgevoerd
[261/356] ophalen data voor paal 300042204
Succes: Delete uitgevoerd
[262/356] ophalen data voor paal 300042205
Succes: Delete uitgevoerd
[263/356] ophalen data voor paal 300042206
Succes: Delete uitgevoerd
[264/356] ophalen data voor paal 300042207
Succes: Delete uitgevoerd
[265/356] ophalen data voor paal 300042208
Geen nieuwe data.
[266/356] ophalen data voor paal 300042209
Succes: Delete uitgevoerd
[267/356] ophalen data voor paal 300042210
Succes: Delete uitgevoerd
[268/356] ophalen data voor paal 300042211
Succes: Delete uitgevoerd
[269/356] ophalen data voor paal 300042212
Succes: Delete uitgevoerd
[270/356] ophalen data voor paal 300042213
Succes: Delete uitgevoerd
[271/356] ophalen data voor paal 300042214
Succes: Delete uitgevoerd
[272/356] ophalen data voor paal 300042215
Geen nieuwe data.
[273/356] ophalen data voor paal 300042216
Succes: Delete uitgevoerd
[274/356] ophalen data voor paal 300042217
Succes: Delete uitgevoerd
[275/356] ophalen data voor paal 300042218
Succes: Delete uitgevoerd
[276/356] ophalen data voor paal 300042219
Succes: Delete uitgevoerd
[277/356] ophalen data voor paal 300042220
Succes: Delete uitgevoerd
[278/356] ophalen data voor paal 300042221
Succes: Delete uitgevoerd
[279/356] ophalen data voor paal 300042222
Succes: Delete uitgevoerd
[280/356] ophalen data voor paal 300042223
Succes: Delete uitgevoerd
[281/356] ophalen data voor paal 300042224
Succes: Delete uitgevoerd
[282/356] ophalen data voor paal 300042225
Succes: Delete uitgevoerd
[283/356] ophalen data voor paal 300042283
Succes: Delete uitgevoerd
[284/356] ophalen data voor paal 300042284
Succes: Delete uitgevoerd
[285/356] ophalen data voor paal 300042636
Succes: Delete uitgevoerd
[286/356] ophalen data voor paal 300042833
Succes: Delete uitgevoerd
[287/356] ophalen data voor paal 300042834
Succes: Delete uitgevoerd
[288/356] ophalen data voor paal 300044090
Succes: Delete uitgevoerd
[289/356] ophalen data voor paal 300044759
Succes: Delete uitgevoerd
[290/356] ophalen data voor paal 300044767
Succes: Delete uitgevoerd
[291/356] ophalen data voor paal 300045245
Succes: Delete uitgevoerd
[292/356] ophalen data voor paal 300045314
Succes: Delete uitgevoerd

In [13]:
df_counts["DateKey"] = df_counts["Date"].dt.strftime("%Y%m%d").astype(int)
df_counts

,CountingPointID,Date,DirectionInCounts,DirectionOutCounts,TotalCounts,DateKey
0,100038932,2026-01-01,602,657,1259,20260101
1,100038932,2026-01-02,1234,1028,2262,20260102
2,100038932,2026-01-03,871,855,1726,20260103
3,100038932,2026-01-04,641,674,1315,20260104
4,100038932,2026-01-05,1868,1767,3635,20260105
...,...,...,...,...,...,...
25969,300064248,2026-03-14,66,61,127,20260314
25970,300064248,2026-03-15,126,122,248,20260315
25971,300064248,2026-03-16,104,103,207,20260316
25972,300064248,2026-03-17,125,146,271,20260317
25973,300064248,2026-03-18,144,152,296,20260318

In [14]:
missing = 356 - len(df_counts["CountingPointID"].unique())
print(missing)

14

In [11]:
fact_counts = df_counts[[
    "CountingPointID",
    "DateKey",
    "DirectionInCounts",
    "DirectionOutCounts",
    "TotalCounts"
]]

In [12]:
print(fact_counts.info())
print(dim_countingpoint.info())

<class 'pandas.DataFrame'>
RangeIndex: 25974 entries, 0 to 25973
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   CountingPointID     25974 non-null  int64
 1   DateKey             25974 non-null  int64
 2   DirectionInCounts   25974 non-null  int64
 3   DirectionOutCounts  25974 non-null  int64
 4   TotalCounts         25974 non-null  int64
dtypes: int64(5)
memory usage: 1014.7 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 356 entries, 0 to 355
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CountingPointID    356 non-null    int64
 1   CustomID           256 non-null    str
 2   CountingPointName  356 non-null    str
 3   Latitude           356 non-null    float64
 4   Longitude          356 non-null    float64
 5   FirstData          356 non-null    object
 6   Granularity        356 non-null    str
 7   Directional        356 non-null    bool
 8   DirectionNameIn    349 non-null    str
 9   DirectionNameOut   337 non-null    str
 10  DomainID           356 non-null    int64
 11  DomainName         356 non-null    str
 12  Description        116 non-null    str
 13  LocationKey        356 non-null    int64
dtypes: bool(1), float64(2), int64(3), object(1), str(7)
memory usage: 36.6+ KB
None